// Bundled offline dataset (province -> waterbody group -> options) of the
// receiving bodies of water an outlet can discharge into, for EMB Region 4-B
// (MIMAROPA). Sourced from EMB's "2020 Updated List of Waterbodies Classified
// and Monitored" (January 2020) and scoped to the same five provinces as
// src/data/mimaropaLocations.ts. Bundled at build time (not fetched at
// runtime) since the app is offline-first.
//
// GENERATED by scripts/generate_waterbodies.py - do not edit by hand. The
// generator refuses to write unless its counts match the totals printed in
// the source PDF's own summary table, so a hand edit here is unverified.
//
// Each option is "Name (Class)" - the classification is what determines
// the effluent standards an outlet is held to, so it travels with the name
// rather than being looked up separately. A waterbody carrying several
// classes is offered once per class: an outlet discharges into one stretch
// of a river, and that stretch's standard is the one that binds.
export interface WaterbodyGroup {
  label: string;
  options: string[];
}

export const WATERBODIES: Record<string, WaterbodyGroup[]> = {
  'Occidental Mindoro': [
    { label: 'Principal Rivers', options: [
      'Busuanga River (C)',
      'Caguray River (A)',
      'Cambaog River (C)',
      'Labangan River (C)',
      'Lumintao River (A)',
      'Magbando River (A)',
      'Mamburao River (A)',
      'Pagbahan River (C)',
    ] },
    { label: 'Minor Rivers', options: [
      'Lawaan River (AA)',
      'Pandurucan River (B)',
      'Sabang River (SC)',
      'Tubaong River (C)',
    ] },
    { label: 'Other Waterbodies', options: [
      'Mangarin Bay (SB)',
      'Mangarin Bay (SC)',
    ] },
  ],
  'Oriental Mindoro': [
    { label: 'Principal Rivers', options: [
      'Agsalin River (C)',
      'Balete River (C)',
      'Bansud River (C)',
      'Banus River (C)',
      'Baroc River (C)',
      'Bongabong River (D)',
      'Bucayao River (C)',
      'Bulalacao River (C)',
      'Butas River (C)',
      'Calapan River (C)',
      'Mag-asawang Tubig River (A)',
      'Malaylay Buco River (A)',
      'Panggalaan River (C)',
      'Pula River (C)',
      'Pulang Tubig River (A)',
      'Samagui River (C)',
    ] },
    { label: 'Minor Rivers', options: [
      'Madugo River (C, assigned)',
      'Pinamalayan River (C, assigned)',
    ] },
    { label: 'Other Waterbodies', options: [
      'Bulalacao Bay (SA)',
      'Calapan Bay (SA)',
      'Calapan Bay (SB)',
      'Muelle Bay (SA)',
      'Naujan Lake (B)',
      'Sabang Bay (SB)',
      'San Isidro Bay (White Beach) (SB)',
    ] },
  ],
  'Marinduque': [
    { label: 'Principal Rivers', options: [
      'Boac River (C)',
      'Tagum River (C)',
      'Tawiran River (A)',
      'Tawiran River (B)',
      'Tawiran River (C)',
    ] },
    { label: 'Minor Rivers', options: [
      'Balanacan River (C)',
      'Mogpog River (C)',
    ] },
    { label: 'Other Waterbodies', options: [
      'Calancan Bay (SB)',
      'Maniwaya Coastal Waters (SB)',
      'Ulan Bay (SB)',
      'Ulan Bay (SC)',
    ] },
  ],
  'Romblon': [
    { label: 'Minor Rivers', options: [
      'Bangon River (C)',
      'Bangon River (SC)',
      'Binayaan River (A)',
      'Bongoy River (SC)',
      'Cabitangahan River (A)',
      'Gabawan River (C)',
      'Talaba River (A)',
    ] },
    { label: 'Other Waterbodies', options: [
      'Cajimos Bay (SC)',
    ] },
  ],
  'Palawan': [
    { label: 'Principal Rivers', options: [
      'Abongan River (C)',
      'Aborlan River (B)',
      'Aborlan River (C)',
      'Apurauan River (B)',
      'Apurauan River (C)',
      'Aramaywan River (Narra Stream) (A)',
      'Aramaywan River (Narra Stream) (C)',
      'Aramaywan River (Quezon Stream) (A)',
      'Aramaywan River (Quezon Stream) (C)',
      'Bacungan River (A)',
      'Bacungan River (B)',
      'Bacungan River (C)',
      'Barbacan River (B)',
      'Barbacan River (C)',
      'Caramay River (B)',
      'Caramay River (C)',
      'Inagauan River (C)',
      'Iwahig River / Ihawig River (A)',
      'Iwahig River / Ihawig River (B)',
      'Lamikan River (A)',
      'Lamikan River (B)',
      'Lamikan River (C)',
      'Langogan River (B)',
      'Malasgao / Malatgao River (A)',
      'Ocayan River (C)',
      'Pandanan River (C)',
      'Panitian River (C)',
      'Pulot River (C)',
      'Quinlogan / Kinlogan River (C)',
      'Rio Tuba River (SC, brackish mangrove)',
      'Rizal River (C)',
      'Tigaplan River (B)',
    ] },
    { label: 'Minor Rivers', options: [
      'Babuyan River (B)',
      'Balitien River (D)',
      'Balsahan River (A)',
      'Balsahan River (B)',
      'Calategas River (A)',
      'Calategas River (C)',
      'Ipilan River (C)',
      'Irawan River (A)',
      'Irawan River (B)',
      'Katubusan River (C)',
      'Maasin River (B)',
      'Maasin River (C)',
      'Malatgao River (A)',
      'Malinao River (A)',
      'Malinao River (B)',
      'Mambalot River (C)',
      'Montible River (A)',
      'Nagsaguipi River (A)',
      'Panacan River (C)',
      'Pinagduguan River (B)',
      'Pinagduguan River (D)',
      'Tagburos River (C)',
      'Tamlang River (B)',
      'Tayuman River (C)',
      'Teretian River (C)',
    ] },
    { label: 'Other Waterbodies', options: [
      'Bacuit Bay (SB)',
      'Coral Bay (SC)',
      'Coron Bay (SB)',
      'Green Island Bay (SB)',
      'Honda Bay (SB)',
      'Imuruan Bay (SB)',
      'Malampaya Sound (SA)',
      'Marine Waters Surrounding Malampaya Platform (SC)',
      'Puerto Princesa Bay (SB)',
      'Snake Island (SB)',
    ] },
  ],
};
